services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    network_mode: "host"
    environment:
      - JELLYFIN_PUBLISHED_PORT=${JELLYFIN_PORT:-8096}
    volumes:
      - ${MEDIA_PATH}:/media
      - ${MEDIA_PATH}/jellyfin_config:/config
      - mnt/nvme/jellyfin-transcodes:/transcodes
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "host"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/London}
      - WEBUI_PORT=${QBIT_WEBUI_PORT:-8080}
      - QBIT_USERNAME=${QBIT_USERNAME:-admin}
      - QBIT_PASSWORD=${QBIT_PASSWORD:-adminadmin}
    volumes:
      - ${MEDIA_PATH}/qbittorrent_config:/config
      - ${MEDIA_PATH}/${DOWNLOADS_PATH}:/downloads
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: "host"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/London}
    volumes:
      - ${MEDIA_PATH}/radarr_config:/config
      - ${MEDIA_PATH}/${MOVIES_PATH}:/movies
      - ${MEDIA_PATH}/${DOWNLOADS_PATH}:/downloads
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "host"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/London}
    volumes:
      - ${MEDIA_PATH}/sonarr_config:/config
      - ${MEDIA_PATH}/${SHOWS_PATH}:/tv
      - ${MEDIA_PATH}/${DOWNLOADS_PATH}:/downloads
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    network_mode: "host"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/London}
    volumes:
      - ${MEDIA_PATH}/jackett_config:/config
      - ${MEDIA_PATH}/${DOWNLOADS_PATH}:/downloads
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    network_mode: "host"
    environment:
      - TZ=${TZ:-Europe/London}
      - LOG_LEVEL=info
    volumes:
      - ${MEDIA_PATH:-./media}/jellyseerr_config:/app/config
    restart: unless-stopped

  netdata:
     image: netdata/netdata:latest
     container_name: netdata
     network_mode: "host"
     cap_add:
       - SYS_PTRACE
       - NET_ADMIN
     security_opt:
       - apparmor=unconfined
     volumes:
       - netdatalib:/var/lib/netdata
       - netdatacache:/var/cache/netdata
       - /etc/passwd:/host/etc/passwd:ro
       - /etc/group:/host/etc/group:ro
       - /proc:/host/proc:ro
       - /sys:/host/sys:ro
       - /etc/os-release:/host/etc/os-release:ro
     restart: unless-stopped

volumes:
  netdatalib:
  netdatacache: